spring.application.name=order
server.port=8083

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DB connection
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator's Health Monitoring
management.endpoints.web.exposure.include=health, beans, mapping, env, metrics, loggers
